version: '3'

#networks:
#  ambientedllo: {}

networks:
  ambientedllo:
    driver: bridge

configs:
  httpd-config:
    external: true

services:
  agentemeli_linux:
    image: aorrego17/agentemeli_linux:beta
    restart: always
    networks:
      - ambientedllo
    ports:
      - "3000:3000"
#    configs:
#      - httpd-config
