version: '3'

#networks:
#  ambientedllo: {}

networks:
  ambientedllo:
    driver: bridge

configs:
  httpd-config:
    external: true

services:
  agentemeli_linux:
    image: aorrego17/agentemeli_linux:v1
    restart: always
    networks:
      - ambientedllo
    ports:
      - "3000:3000"
#    configs:
#      - httpd-config
  
  mongodb_meli:
    image: mongo
    restart: always
    networks:
      - ambientedllo
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password







#    secrets:
#      - server-certificate
#    Dockerfile

#  backend:
#    image: awesome/database
#    volumes:
#      - db-data:/etc/data
#    networks:
#      - back-tier

#volumes:
#  db-data:
#    driver: flocker
#    driver_opts:
#      size: "10GiB"



#secrets:
#  server-certificate:
#    external: true

